### ISSUE TITLE
the purpose of *context_ in plugins

### ISSUE THREAD

**Issue by ClosetGeek-Git** [moslevin/flavr#3]
Each method in the plugin/peripheral API requires a context parameter but I haven't yet found where/how it is used. What's the purpose of this variable?

**Comment by moslevin** [comment]
This was intended to allow a single driver to be used for handling multiple peripherals of the same type with a common driver.  For instance, the context could be used to disambiguate between the 4 UARTs of an ATMega2560 using a single UART driver.  However (as you can tell), I have yet to get around to implementing peripherals in that manner.

**Comment by ClosetGeek-Git** [comment]
Thanks for the quick reply!
