### ISSUE TITLE
EEPROM Example?

### ISSUE THREAD

**Issue by ClosetGeek-Git** [moslevin/flavr#4]
would really love a simple example on how to use EEPROM peripheral plugin. I'm pulling my hair out tying to get any type of output from my simulation. Any quick hints would be great too

**Comment by moslevin** [comment]
I don't have any example code handy, but you can exercise the EEPROM peripheral plugin using the AVR libc EEPROM functions (http://www.nongnu.org/avr-libc/user-manual/group__avr__eeprom.html).  Note that the EEPROM contents aren't persisted to disk or anything (although that could be a future improvement).  

As for getting output from flavr, the UART peripheral will emit its output to your serial console.  It's well-worth implementing a simple polling UART driver to get console-debug functionality.  I have a sample implementation of such a driver in my Mark3 RTOS project's bootloader (https://github.com/moslevin/Mark3/blob/master/bootloader/bootloader.c) -- see the `Serial_` functions.

Regarding debug output from  flAVR itself, there are compile-time macros in most modules that, when enabled, print debugging information to the serial console.  If you're playing with peripheral code, this is usually very helpful to see what's happening in the simulator itself.

**Comment by ClosetGeek-Git** [comment]
Thanks
