### ISSUE TITLE
CPU frequency is not implemented?

### ISSUE THREAD

**Issue by yiivon** [moslevin/flavr#5]
Option --freq and u32CoreFreq property of AVR_CPU are not invoked or refer to in source, is CPU frequency feature do not implemented?

That is, arduino ports function `delay()` will stop the whole loop all the times.

Thanks!

**Comment by moslevin** [comment]
I intended to add the CPU frequency for throttled "real-time" emulation, but never got around to implementing it.  As a result, emulation will run as fast as the host will allow.  

Both 8 and 16-bit timers are implemented, so Arduino's `delay()` functions should work if they use the 8 or 16-bit timer/counters.  The last time I tried using flAVR with Arduino (atmega328p) binaries, delay worked as expected -- unless something's changed in the last couple of years, it should still work fine.  Let me know if it doesn't.

**Comment by yiivon** [comment]
I compiled these codes with Arduino IDE (Arduino UNO) and run the hex file on flavr with(_./flavr --variant atmega328p --uart 1111 --hexfile delay_test.hex_)
```
int addr = 0;

void setup() {
  Serial.begin(9600);
  Serial.println("starting...");
}

void loop() {
  Serial.println("loop begin");

  addr = addr + 1;


  Serial.println(addr);
  delay(1);
  Serial.println("loop end");
}
```
UART output(using tcp porting)
```
starting...
loop begin
1
```
never seen the `loop end` and never loop again.

**Comment by moslevin** [comment]
Found the issue -- Arduino uses Timer0 in fast-PWM mode which flAVR did not support.  I've added logic to support the overflow interrupt used by Arduino in commit f9565b7.

Please checkout the latest master and let me know if that fixes the issue.

**Comment by yiivon** [comment]
Nice job, those codes run correctly, this issue could be closed.

Thanks!
